Repository pingcap/tidb-lightning, pull requests merged in 2019-05, with the labels that each got.

#95 Support table routing rules (merging sharded tables)
  lightning/config/config.go
  lightning/mydump/loader.go
  lightning/mydump/loader_test.go
  lightning/restore/tidb.go
  lightning/restore/tidb_test.go
  tests/routes/config.toml
  tests/routes/data/routes_a0-schema-create.sql
  tests/routes/data/routes_a0.t0-schema.sql
  tests/routes/data/routes_a0.t0.1.sql
  tests/routes/data/routes_a0.t0.2.sql
  tests/routes/data/routes_a0.t1-schema.sql
  tests/routes/data/routes_a0.t1.1.sql
  tests/routes/data/routes_a1-schema-create.sql
  tests/routes/data/routes_a1.s1-schema.sql
  tests/routes/data/routes_a1.s1.sql
  tests/routes/data/routes_a1.t2-schema.sql
  tests/routes/data/routes_a1.t2.sql
  tests/routes/run.sh
  tests/various_types/data/vt.precise_types-schema.sql
  tests/various_types/run.sh
  tidb-lightning.toml
Labels: Should Update Docs, priority/important, status/LGT2, type/feature

#179 tests: removes the emoji from a test database name
  tests/exotic_filenames/data/中文庫-schema-create.sql
  tests/exotic_filenames/data/中文庫.中文表-schema.sql
  tests/exotic_filenames/data/中文庫.中文表.sql
  tests/exotic_filenames/data/中文庫🥳-schema-create.sql
  tests/exotic_filenames/run.sh
Labels: Should Cherry-pick, priority/unimportant, status/LGT2, type/test

#180 *: fix failpoint-ctl path, unify failpoint runtime and ctl to same version
  Makefile
Labels: Should Cherry-pick, priority/normal, status/LGT1, type/enhancement

#178 restore: fix the potential null pointer exception when logging progress
  lightning/restore/restore.go
Labels: priority/normal, status/LGT2, type/bug-fix

#154 kv,restore: log which value caused conversion failure
  lightning/kv/sql2kv.go
  lightning/restore/restore.go
  tests/default-columns/config.toml
  tests/default-columns/run.sh
  tests/sqlmode/on.toml
  tests/sqlmode/run.sh
Labels: priority/normal, status/LGT2, type/enhancement

#182 [2.1] Cherry-pick #180
  Makefile
Labels: 2.1-cherry-pick, priority/unimportant, status/LGT1, type/cherry-pick

#176 restore: retry if deliver KVs to importer
  lightning/restore/restore.go
Labels: Should Cherry-pick, priority/normal, status/LGT2

#173 config: automatically discover tidb.pd-addr and tidb.port if not provided
  cmd/tidb-lightning-ctl/main.go
  lightning/config/config.go
  lightning/config/config_test.go
  tests/restore/config.toml
Labels: priority/normal, status/LGT2, type/enhancement

#184 [2.1] Cherry-pick #176 and #179
  lightning/restore/restore.go
  tests/exotic_filenames/data/中文庫-schema-create.sql
  tests/exotic_filenames/data/中文庫.中文表-schema.sql
  tests/exotic_filenames/data/中文庫.中文表.sql
  tests/exotic_filenames/data/中文庫🥳-schema-create.sql
  tests/exotic_filenames/run.sh
Labels: 2.1-cherry-pick, priority/normal, status/LGT1, type/cherry-pick

#186 common: improve unit test coverage of 'common' package
  lightning/common/util_test.go
  lightning/common/version_test.go
  lightning/log/log.go
Labels: priority/unimportant, qa, status/LGT1, type/test

#187 common: improve unit test coverage of 'kv' package
  lightning/kv/session_test.go
  lightning/kv/sql2kv_test.go
Labels: priority/unimportant, status/LGT1, type/test

#185 Make the parsers stricter, and improve unit test coverage of `mydump` package
  Makefile
  lightning/config/config.go
  lightning/config/config_test.go
  lightning/mydump/csv_parser.rl
  lightning/mydump/csv_parser_generated.go
  lightning/mydump/csv_parser_test.go
  lightning/mydump/parser.go
  lightning/mydump/parser.rl
  lightning/mydump/parser_generated.go
  lightning/mydump/parser_test.go
Labels: priority/normal, status/LGT1, type/enhancement, type/test

#188 lightning: improve unit test coverage of 'lightning' package
  lightning/config/config_test.go
  lightning/lightning_test.go
  lightning/log/log.go
  lightning/log/log_test.go
  lightning/metric/metric_test.go
  lightning/worker/worker_test.go
Labels: priority/unimportant, status/LGT1, type/enhancement, type/test

#192 config: improve unit test coverage of 'config' package
  lightning/config/config_test.go
Labels: priority/normal, status/LGT1, type/enhancement, type/test

#191 Add unit tests for kv/importer and restore/checkpoints, plus some bug fixes
  cmd/tidb-lightning-ctl/main.go
  go.mod
  go.sum
  lightning/common/util.go
  lightning/common/util_test.go
  lightning/kv/importer.go
  lightning/kv/importer_test.go
  lightning/restore/checkpoints.go
  lightning/restore/checkpoints_file_test.go
  lightning/restore/checkpoints_sql_test.go
  lightning/restore/checkpoints_test.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
  lightning/restore/tidb.go
  lightning/restore/tidb_test.go
  mock/importer.go
Labels: priority/normal, status/LGT2, type/bug-fix, type/test

#193 Add unit tests for 'restore.go' (TableRestore and chunkRestore)
  lightning/config/config.go
  lightning/restore/checkreq_test.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
  lightning/restore/testlogger_test.go
Labels: status/LGT2
