Repository pingcap/tidb-lightning, pull requests merged in 2019-07, with the labels that each got.

#200 go.mod: update dependencies
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: priority/unimportant, status/LGT1, type/enhancement

#202 Post restore config fix
  tidb-lightning.toml
Labels: Should Cherry-pick, Should Update Docs, priority/unimportant, status/LGT1, type/doc

#204 [2.1] Cherry-pick #202
  tidb-lightning.toml
Labels: 2.1-cherry-pick, priority/unimportant, status/LGT2, type/cherry-pick

#199 Introduce a basic web interface
  .gitignore
  Makefile
  cmd/tidb-lightning/main.go
  go.mod
  go.sum
  lightning/checkpoints/checkpoints.go
  lightning/checkpoints/checkpoints_file_test.go
  lightning/checkpoints/checkpoints_sql_test.go
  lightning/checkpoints/checkpoints_test.go
  lightning/checkpoints/file_checkpoints.pb.go
  lightning/checkpoints/file_checkpoints.proto
  lightning/checkpoints/tidb.go
  lightning/common/pause.go
  lightning/common/pause_test.go
  lightning/common/util.go
  lightning/common/util_test.go
  lightning/config/configlist.go
  lightning/config/configlist_test.go
  lightning/lightning.go
  lightning/lightning_test.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
  lightning/restore/tidb.go
  lightning/restore/tidb_test.go
  lightning/verification/checksum.go
  lightning/verification/checksum_test.go
  lightning/web/progress.go
  lightning/web/res.go
  lightning/web/res_vfsdata.go
  tools/go.mod
  tools/go.sum
  tools/go_mod_guard.go
  web/README.md
  web/docs/InfoPage.png
  web/docs/ProgressPage.png
  web/docs/TableProgressPage.png
  web/docs/api.yaml
  web/package-lock.json
  web/package.json
  web/public/index.html
  web/src/ChunksProgressPanel.tsx
  web/src/DottedProgress.tsx
  web/src/EnginesProgressPanel.tsx
  web/src/ErrorButton.tsx
  web/src/InfoButton.tsx
  web/src/InfoPage.tsx
  web/src/MoveTaskButton.tsx
  web/src/PauseButton.tsx
  web/src/ProgressPage.tsx
  web/src/RefreshButton.tsx
  web/src/TableProgressCard.tsx
  web/src/TableProgressPage.tsx
  web/src/TaskButton.tsx
  web/src/TitleBar.tsx
  web/src/TitleLink.tsx
  web/src/api.ts
  web/src/index.tsx
  web/src/json-bigint.d.ts
  web/tsconfig.json
  web/webpack.config.js
Labels: Should Update Ansible, Should Update Docs, priority/important, status/LGT2, type/feature

#207 Update README.md
  README.md
Labels: priority/unimportant, status/LGT2, type/doc

#201 Improve errors and logs on syntax error / conversion failure
  lightning/checkpoints/checkpoints.go
  lightning/kv/sql2kv.go
  lightning/kv/sql2kv_test.go
  lightning/log/log_test.go
  lightning/log/testlogger.go
  lightning/mydump/csv_parser.rl
  lightning/mydump/csv_parser_generated.go
  lightning/mydump/csv_parser_test.go
  lightning/mydump/parser.go
  lightning/mydump/parser.rl
  lightning/mydump/parser_generated.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
  lightning/restore/testlogger_test.go
  tests/sqlmode/run.sh
Labels: priority/normal, status/LGT2, type/enhancement

#209 tests,web: exclude these directories from the Go module
  tests/go.mod
  web/go.mod
Labels: priority/unimportant, status/LGT2, type/enhancement

#210 lightning/restore: fix ColumnPermutation calculation
  lightning/restore/restore.go
Labels: status/LGT2, type/bug-fix

#214 *: adjust solution for TOOL-1420 and add a test case
  lightning/kv/sql2kv.go
  lightning/mydump/parser.go
  lightning/mydump/parser_test.go
  lightning/restore/restore.go
  tests/tool_1420/config.toml
  tests/tool_1420/data/EE1420-schema-create.sql
  tests/tool_1420/data/EE1420.pt_role-schema.sql
  tests/tool_1420/data/EE1420.pt_role.sql
  tests/tool_1420/run.sh
Labels: Should Cherry-pick, status/LGT2, type/enhancement, type/test

#206 tests: add test case for simple partitioned tables
  tests/partitioned-table/config.toml
  tests/partitioned-table/data/partitioned-schema-create.sql
  tests/partitioned-table/data/partitioned.a-schema.sql
  tests/partitioned-table/data/partitioned.a.sql
  tests/partitioned-table/run.sh
Labels: priority/unimportant, status/LGT2, type/test

#216 [2.1] *: adjust solution for TOOL-1420 and add a test case (#214)
  lightning/mydump/parser.go
  lightning/restore/restore.go
  tests/tool_1420/config.toml
  tests/tool_1420/data/EE1420-schema-create.sql
  tests/tool_1420/data/EE1420.pt_role-schema.sql
  tests/tool_1420/data/EE1420.pt_role.sql
  tests/tool_1420/run.sh
Labels: 2.1-cherry-pick, priority/unimportant, status/LGT2, type/cherry-pick

#208 checkpoints: remove node_id field and rename the schema on keep-after-success
  lightning/checkpoints/checkpoints.go
  lightning/checkpoints/checkpoints_sql_test.go
  lightning/lightning.go
  lightning/lightning_test.go
  lightning/restore/restore.go
  tests/checkpoint/run.sh
  tests/checkpoint_chunks/file.toml
  tests/checkpoint_chunks/run.sh
Labels: priority/normal, status/LGT2, type/enhancement

#217 config: attempt to solve TOOL-1405 and modify old test cases
  Makefile
  lightning/config/config.go
  lightning/config/config_test.go
  tests/checkpoint/config.toml
  tests/examples/1.toml
  tests/examples/131072.toml
  tests/examples/512.toml
  tests/exotic_filenames/config.toml
  tests/tidb_rowid/config.toml
  tests/unused_config_keys/config.toml
  tests/unused_config_keys/data/unused_config_keys-schema-create.sql
  tests/unused_config_keys/run.sh
Labels: Should Update Docs, feature-request, priority/normal, status/LGT1, type/feature

#218 restore: fix gc life time not recovered after table restore
  lightning/restore/restore.go
  tests/concurrent-restore/config.toml
  tests/concurrent-restore/run.sh
Labels: Should Cherry-pick, priority/normal, status/LGT2, type/bug-fix

#219 restore: fix gc life time not recovered after table restore (#218)
  lightning/restore/restore.go
  tests/concurrent-restore/config.toml
  tests/concurrent-restore/run.sh
Labels: 2.1-cherry-pick, priority/normal, status/LGT2, type/cherry-pick

#215 *: abstract the Importer communication into an interface
  cmd/tidb-lightning-ctl/main.go
  go.mod
  go.sum
  lightning/common/util.go
  lightning/common/util_test.go
  lightning/kv/backend.go
  lightning/kv/backend_test.go
  lightning/kv/importer.go
  lightning/kv/importer_test.go
  lightning/kv/sql2kv.go
  lightning/kv/sql2kv_test.go
  lightning/kv/tikv.go
  lightning/kv/tikv_test.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
  lightning/restore/split_kv_test.go
  mock/backend.go
Labels: priority/important, status/LGT2, type/enhancement
