Repository pingcap/tidb-lightning, pull requests merged in 2019-03, with the labels that each got.

#132 restore: write index kv pairs and data kv pairs to separate engine
  cmd/tidb-lightning-ctl/main.go
  lightning/config/config.go
  lightning/kv/importer.go
  lightning/mydump/parser_generated.go
  lightning/mydump/region.go
  lightning/mydump/region_test.go
  lightning/restore/checkpoints.go
  lightning/restore/file_checkpoints.pb.go
  lightning/restore/file_checkpoints.proto
  lightning/restore/restore.go
  tests/checkpoint/run.sh
  tests/checkpoint_engines/run.sh
  tidb-lightning.toml
Labels: Should Update Ansible, Should Update Docs, priority/important, status/LGT2, type/feature

#111 Support CSV
  Makefile
  lightning/config/config.go
  lightning/mydump/csv_parser.go
  lightning/mydump/csv_parser.rl
  lightning/mydump/csv_parser_generated.go
  lightning/mydump/csv_parser_test.go
  lightning/mydump/loader.go
  lightning/mydump/parser.go
  lightning/mydump/parser_test.go
  lightning/mydump/region.go
  lightning/restore/restore.go
  lightning/restore/tidb.go
  tests/csv/config.toml
  tests/csv/data/csv-schema-create.sql
  tests/csv/data/csv.escapes-schema.sql
  tests/csv/data/csv.escapes.CSV
  tests/csv/data/csv.threads-schema.sql
  tests/csv/data/csv.threads.csv
  tests/csv/run.sh
  tidb-lightning.toml
Labels: Should Update Docs, priority/important, status/LGT2, type/feature

#125 tidb-lightning-ctl: added --import-engine and --cleanup-engine commands
  cmd/tidb-lightning-ctl/main.go
  lightning/kv/importer.go
Labels: Should Update Docs, priority/normal, status/LGT2, type/feature

#141 *: parameter type fix
  cmd/tidb-lightning-ctl/main.go
Labels: priority/unimportant, status/LGT1, type/bug-fix

#146 remove changelog and get change logs from release
  CHANGELOG.md
Labels: priority/unimportant, status/LGT1

#142 test: fix cleanup script to enable re-run integration test locally
  tests/run.sh
Labels: priority/unimportant, qa, status/LGT1, type/enhancement

#147 restore: fix #140 lightning breaks on tidb-master
  go.sum
  lightning/restore/checkreq_test.go
  lightning/restore/restore.go
Labels: priority/unimportant, status/LGT2, type/bug-fix

#149 fix deadlock and goroutine leak in chunk restore
  lightning/restore/restore.go
Labels: status/LGT1, type/bug-fix

#150 restore: eager release index engine worker after imported
  lightning/restore/restore.go
Labels: priority/normal, status/LGT2, type/enhancement

#151 checkpoint: fix checkpoint not updated in some scenario
  lightning/common/util.go
  lightning/mydump/csv_parser.go
  lightning/restore/restore.go
Labels: priority/normal, qa, status/LGT2, type/enhancement

#153 restore: add local checksum log
  lightning/restore/restore.go
Labels: priority/unimportant, status/LGT2, type/enhancement
