Repository pingcap/tidb-lightning, pull requests merged in 2019-04, with the labels that each got.

#158 tests: add kill lightning test in checkpoint_chunks case
  lightning/common/util.go
  lightning/restore/restore.go
  tests/checkpoint_chunks/run.sh
Labels: priority/unimportant, qa, status/PTAL, type/test

#159 tests: fix a test failure due to conflict between #145 and #158
  lightning/restore/restore.go
  tests/checkpoint_chunks/run.sh
Labels: priority/unimportant, qa, status/LGT2, type/test

#156 restore: give priority to small tables for importing
  lightning/metric/metric.go
  lightning/mydump/loader.go
  lightning/restore/restore.go
Labels: priority/important, status/LGT2, type/enhancement

#157 config: Allow overriding some config from command line
  cmd/tidb-lightning-ctl/main.go
  lightning/config/config.go
  lightning/lightning.go
  tests/_utils/run_lightning
  tests/cmdline_override/config.toml
  tests/cmdline_override/data/cmdline_override-schema-create.sql
  tests/cmdline_override/data/cmdline_override.t-schema.sql
  tests/cmdline_override/data/cmdline_override.t.sql
  tests/cmdline_override/run.sh
Labels: priority/normal, status/LGT2, type/feature

#160 go.mod: upgrade dependencies, esp TiDB -> v3.0.0-beta.1
  go.mod
  go.sum
  lightning/common/log.go
  lightning/kv/session.go
Labels: priority/unimportant, status/LGT2, type/enhancement

#161 Fix interpretation of integers in a BIT column
  lightning/mydump/loader_test.go
  lightning/mydump/parser.go
  lightning/mydump/parser.rl
  lightning/mydump/parser_generated.go
  lightning/mydump/parser_test.go
  tests/_utils/run_lightning
  tests/various_types/data/vt.binary.sql
  tests/various_types/data/vt.bit-schema.sql
  tests/various_types/data/vt.bit.sql
  tests/various_types/data/vt.enum-set.sql
  tests/various_types/data/vt.precise_types-schema.sql
  tests/various_types/data/vt.precise_types.sql
  tests/various_types/run.sh
Labels: priority/normal, status/LGT1, type/bug-fix

#165 *: replace gofail with new failpoint implementation
  Makefile
  cmd/tidb-lightning-ctl/main_test.go
  cmd/tidb-lightning/main_test.go
  go.mod
  go.sum
  lightning/kv/importer.go
  lightning/restore/restore.go
  tests/checkpoint/run.sh
  tests/checkpoint_chunks/run.sh
  tests/checkpoint_engines/run.sh
  tests/restore/run.sh
Labels: priority/normal, status/LGT2, type/enhancement

#164 Cherry-pick 2.1: Fix interpretation of integers in a BIT column (#161)
  lightning/mydump/loader_test.go
  lightning/mydump/parser.go
  lightning/mydump/parser.rl
  lightning/mydump/parser_generated.go
  lightning/mydump/parser_test.go
  tests/various_types/data/vt.binary.sql
  tests/various_types/data/vt.bit-schema.sql
  tests/various_types/data/vt.bit.sql
  tests/various_types/data/vt.enum-set.sql
  tests/various_types/data/vt.precise_types-schema.sql
  tests/various_types/data/vt.precise_types.sql
  tests/various_types/run.sh
Labels: 2.1-cherry-pick, priority/important, status/LGT2, type/cherry-pick

#162 *: use pingcap/log (zap) for logging
  cmd/tidb-lightning-ctl/main.go
  cmd/tidb-lightning/main.go
  go.mod
  go.sum
  lightning/common/log.go
  lightning/common/once_error.go
  lightning/common/once_error_test.go
  lightning/common/util.go
  lightning/common/version.go
  lightning/config/config.go
  lightning/kv/importer.go
  lightning/lightning.go
  lightning/log/log.go
  lightning/mydump/csv_parser.rl
  lightning/mydump/csv_parser_generated.go
  lightning/mydump/loader.go
  lightning/mydump/parser.rl
  lightning/mydump/parser_generated.go
  lightning/mydump/reader.go
  lightning/restore/checkpoints.go
  lightning/restore/restore.go
  lightning/restore/tidb.go
  lightning/verification/checksum.go
  tests/error_summary/run.sh
Labels: priority/important, status/LGT2, type/enhancement

#166 Cherry-pick 2.1: Replace gofail with new failpoint implementation (#165)
  Makefile
  cmd/tidb-lightning-ctl/main_test.go
  cmd/tidb-lightning/main_test.go
  go.mod
  go.sum
  lightning/kv/importer.go
  lightning/restore/restore.go
  tests/checkpoint/run.sh
  tests/checkpoint_chunks/run.sh
  tests/checkpoint_engines/run.sh
  tests/restore/run.sh
Labels: 2.1-cherry-pick, priority/important, status/LGT2, type/cherry-pick

#169 [2.1] go.mod: update failpoint dependency to fix integration test failure
  go.mod
  go.sum
Labels: 2.1-cherry-pick, priority/unimportant, status/LGT2, type/bug-fix

#168 main: sync log before exit + update failpoint dep
  cmd/tidb-lightning/main.go
  go.mod
  go.sum
Labels: priority/unimportant, status/LGT1, type/bug-fix

#170 kv: fix handling of column default values
  lightning/kv/sql2kv.go
  tests/default-columns/config.toml
  tests/default-columns/data/defcol-schema-create.sql
  tests/default-columns/data/defcol.t-schema.sql
  tests/default-columns/data/defcol.t.1.sql
  tests/default-columns/data/defcol.t.2.sql
  tests/default-columns/data/defcol.u-schema.sql
  tests/default-columns/data/defcol.u.1.sql
  tests/default-columns/run.sh
Labels: priority/normal, status/LGT2, type/bug-fix

#172 tests,restore: re-enable the exotic_filenames test
  lightning/restore/tidb.go
  tests/exotic_filenames/data/中文庫🥳-schema-create.sql
  tests/exotic_filenames/data/中文庫🥳.中文表-schema.sql
  tests/exotic_filenames/data/中文庫🥳.中文表.sql
  tests/exotic_filenames/run.sh
Labels: priority/normal, qa, status/LGT2, type/bug-fix

#174 [2.1] Cherry-pick #170 and #172
  lightning/kv/sql2kv.go
  lightning/restore/tidb.go
  tests/default-columns/config.toml
  tests/default-columns/data/defcol-schema-create.sql
  tests/default-columns/data/defcol.t-schema.sql
  tests/default-columns/data/defcol.t.1.sql
  tests/default-columns/data/defcol.t.2.sql
  tests/default-columns/data/defcol.u-schema.sql
  tests/default-columns/data/defcol.u.1.sql
  tests/default-columns/run.sh
  tests/exotic_filenames/data/中文庫🥳-schema-create.sql
  tests/exotic_filenames/data/中文庫🥳.中文表-schema.sql
  tests/exotic_filenames/data/中文庫🥳.中文表.sql
  tests/exotic_filenames/run.sh
Labels: 2.1-cherry-pick, priority/normal, status/LGT1, type/cherry-pick

#175 config: reduce default table-concurrency from 8 to 6
  lightning/config/config.go
  tidb-lightning.toml
Labels: Should Update Ansible, priority/unimportant, status/LGT2
