Repository pingcap/tidb-lightning, pull requests merged in 2019-12, with the labels that each got.

#249 Fix +incompatible suffix not allowed error reported by go mod
  go.mod
  go.sum
  tests/go.mod
  web/go.mod
Labels: status/LGT1

#251 allow use a separate pauser instead of global pauser
  lightning/restore/restore.go
  lightning/restore/restore_test.go
Labels: status/LGT2

#253 Add password as command line argument
  lightning/config/config.go
  lightning/config/config_test.go
  lightning/config/global.go
Labels: Should Update Docs, status/LGT1
