Repository pingcap/tidb-lightning, pull requests merged in 2019-08, with the labels that each got.

#220 restore: update and restore GCLifeTime once when parallel
  lightning/restore/restore.go
  lightning/restore/restore_test.go
Labels: Should Cherry-pick, bug, priority/normal, status/LGT1, type/bug-fix

#224 Lance6716/cherry pick 220
  lightning/restore/restore.go
Labels: 2.1-cherry-pick, priority/normal, status/LGT2, status/PTAL, type/cherry-pick

#221 *: support MySQL backend
  cmd/tidb-lightning-ctl/main.go
  lightning/backend/allocator.go
  lightning/backend/backend.go
  lightning/backend/backend_test.go
  lightning/backend/importer.go
  lightning/backend/importer_test.go
  lightning/backend/mysql.go
  lightning/backend/mysql_test.go
  lightning/backend/session.go
  lightning/backend/session_test.go
  lightning/backend/sql2kv.go
  lightning/backend/sql2kv_test.go
  lightning/backend/tikv.go
  lightning/backend/tikv_test.go
  lightning/common/util.go
  lightning/config/config.go
  lightning/config/config_test.go
  lightning/config/global.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
  lightning/restore/tidb.go
  mock/backend.go
  tests/csv/run.sh
  tests/various_types/run.sh
  tidb-lightning.toml
Labels: Should Update Ansible, Should Update Docs, priority/normal, status/LGT2, type/feature

#225 config: always skip the system databases
  lightning/config/config.go
  tests/black-white-list/data/mysql-schema-create.sql
  tests/black-white-list/data/mysql.testtable-schema.sql
  tests/black-white-list/run.sh
Labels: Should Update Docs, status/LGT2, type/enhancement

#228 backend: update mysql backend to tidb backend
  lightning/backend/tidb.go
  lightning/backend/tidb_test.go
  lightning/config/config.go
  lightning/restore/restore.go
  tests/csv/run.sh
  tests/various_types/run.sh
  tidb-lightning.toml
Labels: priority/unimportant, status/LGT2

#229 lightning/common: add unit test
  lightning/common/util_test.go
Labels: priority/unimportant, status/LGT2, type/test

#226 mock: update rpc endpoint
  go.mod
  go.sum
  mock/importer.go
Labels: priority/unimportant, status/LGT2

#230 cmd: do not exit(1) if failed to sync log
  cmd/tidb-lightning/main.go
Labels: Should Cherry-pick, priority/unimportant, status/LGT2, type/bug-fix

#234 mock: update rpc endpoint
  go.mod
  go.sum
  mock/importer.go
Labels: priority/unimportant, status/LGT2

#227 backend: dynamically calculate the maximum auto-inc ID
  lightning/backend/sql2kv.go
  lightning/backend/sql2kv_test.go
  lightning/restore/restore.go
  tests/tool_1472/config.toml
  tests/tool_1472/data/EE1472-schema-create.sql
  tests/tool_1472/data/EE1472.notpk-schema.sql
  tests/tool_1472/data/EE1472.notpk.1.sql
  tests/tool_1472/data/EE1472.notpk.2.sql
  tests/tool_1472/data/EE1472.pk-schema.sql
  tests/tool_1472/data/EE1472.pk.1.sql
  tests/tool_1472/data/EE1472.pk.2.sql
  tests/tool_1472/run.sh
Labels: status/LGT2, type/bug-fix
