Repository pingcap/tidb-lightning, pull requests merged in 2020-09, with the labels that each got.

#375 Fix running unit tests on Windows
  lightning/backend/local_unix.go
  lightning/backend/local_windows.go
  lightning/lightning.go
  lightning/lightning_test.go
  lightning/mydump/loader.go
  tidb-lightning.toml
Labels: status/LGT1

#376 checkpoint: verify checkpoint when resume from checkpoint
  lightning/checkpoints/checkpoints.go
  lightning/checkpoints/checkpoints_file_test.go
  lightning/checkpoints/checkpoints_sql_test.go
  lightning/checkpoints/checkpoints_test.go
  lightning/checkpoints/file_checkpoints.pb.go
  lightning/checkpoints/file_checkpoints.proto
  lightning/lightning.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
Labels: status/LGT2

#382 test: change integration test script to allow run tests in parallel
  tests/run.sh
Labels: status/LGT2

#369 backend: split and ingest region size more precise
  lightning/backend/local.go
  lightning/backend/localhelper.go
Labels: status/LGT2

#386 checkpoint: wait checkpoint finished if exit before success
  lightning/restore/restore.go
Labels: status/LGT2

#361 restore: support restore from s3
  cmd/tidb-lightning/main.go
  go.mod
  go.sum
  lightning/backend/checkreq_test.go
  lightning/backend/importer_test.go
  lightning/checkpoints/file_checkpoints.pb.go
  lightning/common/once_error_test.go
  lightning/common/pause_test.go
  lightning/common/version.go
  lightning/common/version_test.go
  lightning/config/config.go
  lightning/config/config_test.go
  lightning/config/configlist_test.go
  lightning/config/global.go
  lightning/lightning.go
  lightning/lightning_test.go
  lightning/log/log_test.go
  lightning/metric/metric_test.go
  lightning/mydump/csv_parser.go
  lightning/mydump/loader.go
  lightning/mydump/loader_test.go
  lightning/mydump/parser.go
  lightning/mydump/parser_test.go
  lightning/mydump/reader.go
  lightning/mydump/reader_test.go
  lightning/mydump/region.go
  lightning/mydump/region_test.go
  lightning/mydump/router.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
  lightning/web/progress.go
  lightning/worker/worker_test.go
  mock/backend.go
  mock/importer.go
  tests/file_routing/config.toml
  tests/file_routing/run.sh
  tests/s3/config.toml
  tests/s3/run.sh
Labels: status/LGT1

#387 backend: fix sample when split region size is small
  lightning/backend/local.go
  tests/_utils/check_cluster_version
  tests/checkpoint/run.sh
  tests/common_handle/run.sh
  tests/run.sh
  tests/s3/run.sh
Labels: status/LGT2

#392 backend: use peer address as grpc addr for tiflash store
  lightning/backend/local.go
  tests/README.md
  tests/_utils/check_cluster_version
  tests/run.sh
  tests/tiflash/config.toml
  tests/tiflash/run.sh
Labels: release-blocker, status/LGT2

#394 loader: fix store.WalkDir return inaccurate file size for soft link source files
  go.mod
  go.sum
  lightning/checkpoints/checkpoints.go
  lightning/checkpoints/checkpoints_sql_test.go
  tests/source_linkfile/config.toml
  tests/source_linkfile/run.sh
Labels: status/LGT2

#395 checkpoint: fix chunk checkpoint may reset offset and row id
  lightning/restore/restore.go
Labels: status/LGT2

#397 make tiflash test more stable
  tests/run.sh
Labels: status/LGT2

#390 test: fix integration test for 3.x version
  tests/checkpoint_error_destroy/file.toml
  tests/checkpoint_error_destroy/run.sh
  tests/common_handle/run.sh
  tests/file_routing/run.sh
Labels: status/LGT2

#398 test: make start tiflash optional in integration test
  tests/README.md
  tests/run.sh
  tests/source_linkfile/run.sh
  tests/tiflash/run.sh
Labels: status/LGT2

#373 restore: support restore apache parquet format source files
  Makefile
  go.mod
  go.sum
  lightning/mydump/loader.go
  lightning/mydump/parquet_parser.go
  lightning/mydump/parquet_parser_test.go
  lightning/mydump/region.go
  lightning/mydump/router.go
  lightning/restore/restore.go
  tests/_utils/run_sql
  tests/checkpoint_parquet/config.toml
  tests/checkpoint_parquet/parquet.go
  tests/checkpoint_parquet/run.sh
  tests/parquet/config.toml
  tests/parquet/data/export_info_ci.json
  tests/parquet/data/export_tables_info_ci_from_1_to_9.json
  tests/parquet/data/test/test.customer/_SUCCESS
  tests/parquet/data/test/test.customer/part-00000-c3744aeb-351c-49ba-bdf3-5864befff481-c000.gz.parquet
  tests/parquet/data/test/test.district/_SUCCESS
  tests/parquet/data/test/test.district/part-00000-f61f4bef-6765-432a-8f18-cd17b4607f2a-c000.gz.parquet
  tests/parquet/data/test/test.history/_SUCCESS
  tests/parquet/data/test/test.history/part-00000-8cf0e97a-1169-4335-a93f-8805e02def97-c000.gz.parquet
  tests/parquet/data/test/test.item/_SUCCESS
  tests/parquet/data/test/test.item/part-00000-8905ded8-4c54-477f-9907-6e3eae50358b-c000.gz.parquet
  tests/parquet/data/test/test.new_order/_SUCCESS
  tests/parquet/data/test/test.new_order/part-00000-d868200e-b629-4445-bd96-d34b6674b09d-c000.gz.parquet
  tests/parquet/data/test/test.order_line/_SUCCESS
  tests/parquet/data/test/test.order_line/part-00000-e36fecd0-3f59-4ff6-b271-2e4b27ffbcf5-c000.gz.parquet
  tests/parquet/data/test/test.orders/_SUCCESS
  tests/parquet/data/test/test.orders/part-00000-b45481f5-92c0-4961-9bf7-32a0a04ffee5-c000.gz.parquet
  tests/parquet/data/test/test.stock/_SUCCESS
  tests/parquet/data/test/test.stock/part-00000-eef45943-3034-4d65-b375-ee55aa479215-c000.gz.parquet
  tests/parquet/data/test/test.warehouse/_SUCCESS
  tests/parquet/data/test/test.warehouse/part-00000-c6c33252-4d2f-4c5c-8a2f-d162bde6c360-c000.gz.parquet
  tests/parquet/db.sql
  tests/parquet/run.sh
  tidb-lightning.toml
Labels: Should Update Docs, status/LGT2

#402 backend: fix load partition table with local backend
  lightning/backend/local.go
  tests/common_handle/run.sh
  tests/parquet/run.sh
  tests/partitioned-table/config.toml
  tests/partitioned-table/data/partitioned.a-schema.sql
  tests/partitioned-table/data/partitioned.a.sql
  tests/partitioned-table/run.sh
  tests/tiflash/run.sh
Labels: status/LGT2

#393 lightning: support dynamically modifying the log level
  go.sum
  lightning/lightning.go
  lightning/log/log.go
  web/docs/api.yaml
Labels: Should Update Docs, status/LGT2

#383 Check Lightning version when reusing checkpoint
  go.sum
  lightning/checkpoints/checkpoints.go
  lightning/checkpoints/checkpoints_sql_test.go
  lightning/checkpoints/file_checkpoints.pb.go
  lightning/checkpoints/file_checkpoints.proto
  lightning/mydump/loader.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
Labels: status/LGT2

#407 support new collation for kv encoder
  lightning/restore/restore.go
  lightning/restore/tidb.go
  lightning/restore/tidb_test.go
  tests/_utils/run_services
  tests/new_collation/config.toml
  tests/new_collation/run.sh
  tests/run.sh
Labels: status/LGT2

#406 mydump: support multi bytes csv delimiter and separator
  lightning/config/config.go
  lightning/config/config_test.go
  lightning/lightning_test.go
  lightning/mydump/bytes.go
  lightning/mydump/csv_parser.go
  lightning/mydump/csv_parser_test.go
  lightning/mydump/region_test.go
  tidb-lightning.toml
Labels: Should Update Docs, status/LGT2

#405 backend: always retry ingest and get region if it's retryble
  lightning/backend/local.go
Labels: status/LGT2
