Repository pingcap/tidb-lightning, pull requests merged in 2020-08, with the labels that each got.

#364 parser: fix csv parse header with empty line
  lightning/mydump/csv_parser.go
  lightning/mydump/csv_parser_test.go
  lightning/mydump/region.go
  lightning/restore/restore.go
Labels: status/LGT1

#362 restore: fix missing colum infos when restore from checkpoint
  lightning/checkpoints/checkpoints.go
  lightning/checkpoints/checkpoints_sql_test.go
  lightning/mydump/parser.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
  tests/checkpoint_columns/config.toml
  tests/checkpoint_columns/run.sh
Labels: status/LGT1

#367 local: fix import with common handle
  go.mod
  go.sum
  lightning/backend/local.go
  lightning/backend/session.go
  lightning/backend/sql2kv.go
  tests/common_handle/config.toml
  tests/common_handle/run.sh
Labels: status/LGT1

#368 restore: don't switch mode in tidb backend
  lightning/restore/restore.go
Labels: status/LGT2

#363 restore: support split csv source file with header
  lightning/mydump/csv/split_large_file.csv
  lightning/mydump/csv_parser.go
  lightning/mydump/parser.go
  lightning/mydump/region.go
  lightning/mydump/region_test.go
  lightning/restore/restore.go
Labels: status/LGT2

#366 restore: support file level routing
  lightning/checkpoints/checkpoints.go
  lightning/checkpoints/checkpoints_file_test.go
  lightning/checkpoints/checkpoints_sql_test.go
  lightning/checkpoints/file_checkpoints.pb.go
  lightning/checkpoints/file_checkpoints.proto
  lightning/config/config.go
  lightning/lightning_test.go
  lightning/mydump/loader.go
  lightning/mydump/loader_test.go
  lightning/mydump/reader.go
  lightning/mydump/region.go
  lightning/mydump/region_test.go
  lightning/mydump/router.go
  lightning/mydump/router_test.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
  tests/file_routing/config.toml
  tests/file_routing/run.sh
  tidb-lightning.toml
Labels: status/LGT2

#371 tidb_tools: update dependency
  go.mod
  go.sum
Labels: status/LGT2

#372 restore: check header columns
  lightning/restore/restore.go
  lightning/restore/restore_test.go
Labels: status/LGT2

#374 web: update dependencies
  lightning/web/res_vfsdata.go
  web/package-lock.json
  web/package.json
Labels: status/LGT2

#379 backend: use pd tso as commit ts in local and importer backend
  lightning/backend/backend.go
Labels: status/PTAL, type/bug-fix

#380 update pd dependencies
  go.mod
  go.sum
  lightning/backend/local.go
  lightning/common/security.go
  lightning/mydump/router.go
Labels: status/LGT2

#381 local: return error if write to tikv returns no leader info
  lightning/backend/backend.go
  lightning/backend/local.go
Labels: status/LGT2

#378 encoder: check string value for tidb encoder
  lightning/backend/tidb.go
  lightning/backend/tidb_test.go
Labels: status/LGT2
