Repository pingcap/tidb-lightning, pull requests merged in 2020-10, with the labels that each got.

#414 mydump: fix infinite loop in ExportStatement when Read() returns an error but is not EOF
  lightning/mydump/reader.go
  lightning/mydump/reader_test.go
  mock/importer.go
  mock/storage.go
Labels: status/LGT2

#415 lightning: start the HTTP server when receiving SIGUSR1
  lightning/lightning.go
  lightning/sigusr1_other.go
  lightning/sigusr1_unix.go
Labels: Should Update Docs, status/LGT1

#412 backend/tidb: fix issue 410
  lightning/backend/tidb.go
  tests/issue_410/config.toml
  tests/issue_410/data/issue410-schema-create.sql
  tests/issue_410/data/issue410.row_flow_d-schema.sql
  tests/issue_410/data/issue410.row_flow_d.0.csv
  tests/issue_410/run.sh
Labels: 3.0-release-note, 4.0-release-note, status/LGT1

#411 config: fix error on `-d 'C:\Windows\Path'`
  go.sum
  lightning/config/config.go
  lightning/lightning_test.go
  lightning/mydump/loader_test.go
Labels: status/LGT2

#418 local: fix infinity loop in retry get region
  go.mod
  go.sum
  lightning/backend/local.go
  mock/storage.go
  tools/go.mod
  tools/go.sum
Labels: status/LGT2

#400 backend: speed up uploading by open multi TCP connections
  lightning/backend/local.go
Labels: status/LGT2

#421 post-restore: add optional level for post-restore operations
  lightning/config/config.go
  lightning/config/config_test.go
  lightning/config/global.go
  lightning/restore/restore.go
  tidb-lightning.toml
Labels: Should Update Docs, status/LGT2

#419 backend/local: do not retry epochNotMatch error when ingest sst
  lightning/backend/local.go
  lightning/backend/local_test.go
Labels: status/LGT2

#408 restore: disable some pd scheduler during restore
  go.mod
  go.sum
  lightning/restore/restore.go
Labels: status/LGT2

#425 log: simplify some warn log and do retry write for epoch not match error
  lightning/backend/local.go
  lightning/backend/localhelper.go
Labels: status/LGT2

#426 test: fix a unstable integration test
  tests/_utils/run_services
  tests/row-format-v2/run.sh
Labels: status/LGT2

#420 backend: fix a bug about wrong column info
  lightning/backend/tidb.go
  tests/too_many_columns/config.toml
  tests/too_many_columns/data/too_many_columns-schema-create.sql
  tests/too_many_columns/data/too_many_columns.t-schema.sql
  tests/too_many_columns/data/too_many_columns.t.0.csv
  tests/too_many_columns/run.sh
Labels: status/LGT2

#377 restore: better estimate task remain time progress log
  lightning/restore/restore.go
Labels: status/LGT2

#396 checksum: use gc ttl api for checksum gc safepoint in v4.0 cluster
  lightning/backend/importer.go
  lightning/checkpoints/tidb.go
  lightning/common/version.go
  lightning/restore/checksum.go
  lightning/restore/checksum_test.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
  lightning/restore/tidb.go
  lightning/restore/tidb_test.go
Labels: status/LGT2

#428 backend/tidb: add rebase auto id for tidb backend
  lightning/backend/backend.go
  lightning/backend/checkreq_test.go
  lightning/backend/importer.go
  lightning/backend/local.go
  lightning/backend/tidb.go
  lightning/backend/tidb_test.go
  lightning/common/version.go
  lightning/common/version_test.go
  lightning/restore/checksum.go
  lightning/restore/restore.go
  lightning/restore/tidb.go
  lightning/restore/tidb_test.go
  mock/backend.go
  tests/alter_random/run.sh
Labels: status/LGT1

#430 backend/tidb: fix compatible issue in fetch table schemas
  lightning/backend/tidb.go
  lightning/backend/tidb_test.go
Labels: status/LGT2
