Repository pingcap/tidb-lightning, pull requests merged in 2020-12, with the labels that each got.

#499 test: fix can not kill tiflash process by name
  tests/_utils/run_services
Labels: status/LGT1

#498 .github: let challenge-bot recognize the default SIG
  .github/challenge-bot.yml
Labels: status/LGT2

#505 backend: support stored generated columns in local/importer backends
  lightning/backend/backend.go
  lightning/backend/backend_test.go
  lightning/backend/importer.go
  lightning/backend/local.go
  lightning/backend/session.go
  lightning/backend/sql2kv.go
  lightning/backend/sql2kv_test.go
  lightning/backend/tidb.go
  lightning/backend/tidb_test.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
  mock/backend.go
  tests/_utils/run_sql
  tests/generated_columns/config.toml
  tests/generated_columns/data/gencol-schema-create.sql
  tests/generated_columns/data/gencol.nested-schema.sql
  tests/generated_columns/data/gencol.nested.0.sql
  tests/generated_columns/data/gencol.various_types-schema.sql
  tests/generated_columns/data/gencol.various_types.0.sql
  tests/generated_columns/run.sh
  tests/restore/run.sh
Labels: status/LGT2

#497 backend/local: check and return iter.Error when pebble is not valid
  lightning/backend/local.go
Labels: status/LGT2

#508 backend,restore: duplicate more important system variables from downstream
  lightning/backend/backend_test.go
  lightning/backend/session.go
  lightning/backend/session_test.go
  lightning/backend/sql2kv.go
  lightning/backend/sql2kv_test.go
  lightning/backend/tidb_test.go
  lightning/glue/glue.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
  lightning/restore/tidb.go
  lightning/restore/tidb_test.go
  tests/_utils/read_result
  tests/auto_random_default/run.sh
  tests/generated_columns/data/gencol.various_types-schema.sql
  tests/generated_columns/run.sh
Labels: status/LGT2

#501 backend/local: set pebble db max file limit
  lightning/backend/local.go
  lightning/backend/local_unix.go
  lightning/backend/local_windows.go
  lightning/lightning.go
  lightning/lightning_test.go
  lightning/restore/restore.go
Labels: status/LGT2

#521 mydump: fix issue 519
  lightning/mydump/csv_parser.go
  lightning/mydump/csv_parser_test.go
  tests/issue_519/config.toml
  tests/issue_519/data/issue519-schema-create.sql
  tests/issue_519/data/issue519.t-schema.sql
  tests/issue_519/data/issue519.t.csv
  tests/issue_519/run.sh
Labels: CanMerge, release-blocker, status/LGT2

#516 backend/local: remove useless and buggy truncate key
  lightning/backend/localhelper.go
  lightning/backend/localhelper_test.go
Labels: CanMerge, status/LGT2

#517 restore: apply adjust max-pending-peer-count when stop pd schedulers
  go.mod1
  go.sum1
Labels: CanMerge, release-blocker, status/LGT2

#523 backend/local: fix next key
  lightning/backend/local.go
  lightning/backend/local_test.go
  tests/various_types/data/vt.precise_types-schema.sql
  tests/various_types/run.sh
Labels: status/LGT2

#526 backend: import planner/core package to initialize expression.RewriteAstExpr
  lightning/backend/sql2kv.go
  lightning/restore/restore.go
Labels: first-time-contributor, status/LGT2

#527 *: add some error description
  lightning/backend/local.go
  lightning/backend/localhelper.go
  lightning/lightning.go
  lightning/lightning_test.go
  lightning/mydump/loader.go
  lightning/mydump/loader_test.go
  lightning/restore/restore.go
Labels: CanMerge, status/LGT2

#529 test: fix unstable integration test auto_random_default
  tests/auto_random_default/run.sh
Labels: CanMerge, status/LGT2

#509 post-process: support run table analyze after all tables are finished
  lightning/config/config.go
  lightning/restore/restore.go
  tidb-lightning.toml
Labels: status/LGT1

#531 backend/local: add encode for retry scan region keys
  lightning/backend/localhelper.go
  lightning/backend/localhelper_test.go
Labels: status/LGT1, type/bug-fix

#530 restore: fix error lost in create schema
  lightning/restore/tidb.go
  lightning/restore/tidb_test.go
Labels: CanMerge, status/LGT2, type/bug-fix

#533 mydumper: update br to apply auto retry s3 read error
  go.mod1
  go.sum1
Labels: CanMerge, status/LGT2

#520 Sort index rather than insert it into skiplist
  lightning/backend/backend.go
  lightning/backend/backend_test.go
  lightning/backend/importer.go
  lightning/backend/local.go
  lightning/backend/local_test.go
  lightning/backend/tidb.go
  lightning/config/config.go
  lightning/lightning_test.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
  mock/backend.go
Labels: first-time-contributor, status/LGT2

#538 *: redact log and error messages, add log-redact parameter
  lightning/backend/local.go
  lightning/backend/localhelper.go
  lightning/backend/sql2kv.go
  lightning/backend/sql2kv_test.go
  lightning/backend/tidb.go
  lightning/config/global.go
  lightning/log/log.go
  lightning/log/redact.go
  tidb-lightning.toml
Labels: Should Update Docs, status/LGT2, status/PTAL

#535 mydumper: do not remove more than 1 sep if trim last sep is true
  lightning/mydump/csv_parser.go
  lightning/mydump/csv_parser_test.go
Labels: CanMerge, status/LGT2

#537 restore: add error retry for checksum by tikv
  lightning/restore/checksum.go
  lightning/restore/checksum_test.go
Labels: status/LGT2
