Repository pingcap/tidb-lightning, pull requests merged in 2020-03, with the labels that each got.

#276 Update Chinese doc url
  README.md
Labels: priority/unimportant, status/LGT1, type/doc

#280 Make sure the session param takes effect
  lightning/common/util.go
  lightning/common/util_test.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
  lightning/restore/tidb.go
Labels: status/LGT1

#272 lightning: split large csv file if possible
  lightning/config/config.go
  lightning/config/const.go
  lightning/mydump/csv/split_large_file.csv
  lightning/mydump/csv_parser.go
  lightning/mydump/csv_parser_generated.go
  lightning/mydump/parser_generated.go
  lightning/mydump/region.go
  lightning/mydump/region_test.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
Labels: 3.0-release-note, 3.1-release-note, 4.0-release-note, Should Update Ansible, Should Update Docs, priority/normal, status/LGT1, type/enhancement

#279 send a batch of kv in encodeLoop
  lightning/config/config.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
Labels: status/LGT2, type/enhancement

#275 Replace CSV Ragel parser by a hand-written parser copied from encoding/csv
  Makefile
  lightning/mydump/csv_parser.go
  lightning/mydump/csv_parser.rl
  lightning/mydump/csv_parser_generated.go
  lightning/mydump/csv_parser_test.go
  lightning/mydump/parser.go
  lightning/mydump/parser_test.go
  lightning/mydump/reader.go
  lightning/mydump/region.go
  lightning/restore/restore.go
Labels: priority/normal, status/LGT1, type/enhancement

#283 backend: fix issue 282
  lightning/backend/tidb.go
  lightning/backend/tidb_test.go
  lightning/mydump/parser.go
  lightning/mydump/parser_test.go
  tests/check_requirements/run.sh
  tests/checkpoint_chunks/run.sh
  tests/issue_282/config.toml
  tests/issue_282/data/issue282-schema-create.sql
  tests/issue_282/data/issue282.t_access3-schema.sql
  tests/issue_282/data/issue282.t_access3.sql
  tests/issue_282/run.sh
Labels: 3.0-release-note, 3.1-release-note, 4.0-release-note, priority/important, status/LGT1, type/bug-fix

#281 optimize the performance of lightning
  cmd/tidb-lightning/main.go
  go.mod
  go.sum
  lightning/backend/importer.go
  lightning/backend/importer_test.go
  lightning/backend/session.go
  lightning/mydump/csv_parser.go
  lightning/mydump/parser.go
  lightning/restore/restore.go
  tools/go.mod
  tools/go.sum
Labels: status/LGT1
