Repository pingcap/tidb-lightning, pull requests merged in 2020-04, with the labels that each got.

#287 Some SwitchMode improvements
  cmd/tidb-lightning-ctl/main.go
  lightning/backend/tikv.go
  lightning/backend/tikv_test.go
Labels: 3.0-release-note, 3.1-release-note, 4.0-release-note, Should Update Docs, priority/normal, status/LGT2, type/feature

#289 go.mod,web: update dependencies
  go.mod
  go.sum
  lightning/backend/sql2kv_test.go
  lightning/common/util.go
  lightning/common/util_test.go
  lightning/restore/restore_test.go
  lightning/web/res_vfsdata.go
  tools/go.mod
  tools/go.sum
  web/package-lock.json
  web/package.json
  web/src/TaskButton.tsx
Labels: priority/unimportant, status/LGT2, type/enhancement

#295 Support store version format generated by `git describe --tags`
  lightning/restore/checkreq_test.go
  lightning/restore/restore.go
Labels: 3.1-release-note, 4.0-release-note, status/LGT2, type/bug-fix
