Repository pingcap/tidb-lightning, pull requests merged in 2020-06, with the labels that each got.

#324 support alter random && update tidb dependency to latest
  go.mod
  go.sum
  lightning/backend/session.go
  lightning/backend/sql2kv.go
  lightning/backend/sql2kv_test.go
  lightning/checkpoints/checkpoints_sql_test.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
  lightning/restore/tidb.go
  lightning/restore/tidb_test.go
  tests/alter_random/config.toml
  tests/alter_random/data/alter_random-schema-create.sql
  tests/alter_random/data/alter_random.t-schema.sql
  tests/alter_random/data/alter_random.t.sql
  tests/alter_random/run.sh
  tests/run.sh
  tools/go.mod
  tools/go.sum
Labels: Should Cherry-pick, status/LGT2

#328 make lightning compatible with allow_auto_random_explicit_insert
  lightning/.DS_Store
  lightning/backend/session.go
  lightning/backend/sql2kv.go
  lightning/restore/tidb.go
Labels: status/LGT2

#331 config: update example config file
  lightning/config/config.go
  tidb-lightning.toml
Labels: status/LGT2

#334 optimize parse csv and local backend write tikv
  go.mod
  go.sum
  lightning/backend/local.go
  lightning/mydump/bytes.go
  lightning/mydump/csv_parser.go
Labels: status/LGT2

#336 wait checkpoint routine finish before cleanup
  lightning/lightning.go
  lightning/restore/restore.go
Labels: status/LGT1

#337 lightning: fix web page not showing when not using server mode
  lightning/lightning.go
Labels: status/LGT2, status/PTAL, type/bug-fix

#332 config,mydumper: replace black-white-list by table-filter
  go.mod
  go.sum
  lightning/config/config.go
  lightning/config/global.go
  lightning/lightning_test.go
  lightning/mydump/loader.go
  lightning/mydump/loader_test.go
  lightning/mydump/region_test.go
  tests/black-white-list/config.toml
  tests/black-white-list/run.sh
  tidb-lightning.toml
Labels: 3.0-release-note, 3.1-release-note, 4.0-release-note, Should Update Docs, status/LGT2

#338 optimize encoder and adjust some config
  go.mod
  go.sum
  lightning/backend/local.go
  lightning/backend/session.go
  lightning/backend/sql2kv.go
  lightning/config/config.go
  tests/local_backend/config.toml
  tidb-lightning.toml
  tools/go.mod
  tools/go.sum
Labels: Should Update Docs, status/LGT1
