Repository pingcap/tidb-lightning, pull requests merged in 2020-07, with the labels that each got.

#345 log: fix log file path
  cmd/tidb-lightning/main.go
  lightning/config/global.go
  lightning/log/log.go
  tidb-lightning.toml
Labels: Should Update Ansible, Should Update Docs, status/LGT2

#347 backend: fix local backend may divide by 0
  lightning/backend/local.go
Labels: status/LGT2

#340 add log for environment http proxy setting
  lightning/lightning.go
Labels: status/LGT2

#348 post-process: only update auto increment id when needed
  lightning/restore/restore.go
Labels: status/LGT1

#343 server: check open file ulimit for local backend
  go.mod
  lightning/backend/local.go
  lightning/lightning.go
  lightning/lightning_test.go
Labels: status/LGT1

#349 restore: do not rebase auto-id or generate auto row id for table with common handle
  lightning/backend/sql2kv.go
  lightning/common/util.go
  lightning/restore/restore.go
Labels: status/LGT2

#352 Fix verbose log message for shell
  cmd/tidb-lightning/main.go
Labels: status/LGT2

#356 local: fix batch split retry alway failed error
  lightning/backend/localhelper.go
Labels: status/LGT2

#357 backend/tidb: fix handling of empty binary literals
  lightning/backend/tidb.go
  lightning/backend/tidb_test.go
  tests/various_types/data/vt.binary.sql
  tests/various_types/run.sh
Labels: status/LGT2

#359 backend/tidb: add log when execute statement failed
  lightning/backend/tidb.go
Labels: status/LGT2

#354 lightning: check checkpoint schema conflict
  lightning/checkpoints/checkpoints.go
  lightning/lightning.go
  lightning/lightning_test.go
Labels: status/LGT2
