Repository pingcap/tidb-lightning, pull requests merged in 2020-05, with the labels that each got.

#315 Warn for single large file, change switch mode log level to info
  lightning/backend/tikv.go
  lightning/mydump/region.go
Labels: status/LGT1

#304 restore: fix a typo about the recommended action on checkpoint error.
  lightning/restore/restore.go
  tests/error_summary/run.sh
Labels: priority/unimportant, status/LGT2, type/bug-fix

#313 print lightning log to local file
  cmd/tidb-lightning/main.go
  lightning/config/global.go
  lightning/restore/restore.go
Labels: status/PTAL

#312 *: avoid accessing internal ports when backend=tidb
  lightning/backend/backend.go
  lightning/backend/checkreq_test.go
  lightning/backend/importer.go
  lightning/backend/tidb.go
  lightning/checkpoints/file_checkpoints.pb.go
  lightning/checkpoints/tidb.go
  lightning/config/config.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
  lightning/restore/tidb.go
  lightning/restore/tidb_test.go
  mock/backend.go
Labels: priority/normal, status/LGT1, type/enhancement

#316 config: remove strict mode from default SQL mode
  lightning/config/config.go
  tests/sqlmode/on.toml
Labels: Should Update Docs, priority/unimportant, status/LGT2, type/enhancement

#317 check table id when loading checkpoint
  lightning/checkpoints/checkpoints.go
  lightning/checkpoints/checkpoints_sql_test.go
  lightning/checkpoints/file_checkpoints.pb.go
  lightning/checkpoints/file_checkpoints.proto
  lightning/restore/restore.go
  tests/checkpoint/run.sh
  tests/checkpoint_chunks/run.sh
  tests/checkpoint_dirty_tableid/data/cpdt-schema-create.sql
  tests/checkpoint_dirty_tableid/data/cpdt.t-schema.sql
  tests/checkpoint_dirty_tableid/data/cpdt.t.sql
  tests/checkpoint_dirty_tableid/file.toml
  tests/checkpoint_dirty_tableid/mysql.toml
  tests/checkpoint_dirty_tableid/run.sh
Labels: status/PTAL

#319 update tidb-tools to latest
  go.mod
  go.sum
Labels: Should Cherry-pick, status/LGT2, type/bug-fix
