Repository pingcap/tidb-lightning, pull requests merged in 2021-01, with the labels that each got.

#540 post-process: allow run checksum at last and restrict the number of checksum jobs
  lightning/config/config.go
  lightning/restore/restore.go
  tidb-lightning.toml
Labels: CanMerge, status/LGT2

#545 restore: don't change TiDB config to support lightning via SQL
  lightning/restore/checksum.go
  lightning/restore/restore.go
Labels: status/LGT2

#528 restore: check row value count to avoid unexpected encode result
  go.mod1
  go.sum1
  lightning/backend/tidb.go
  lightning/backend/tidb_test.go
  lightning/mydump/parser.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
  lightning/restore/tidb.go
  tests/tidb_rowid/run.sh
Labels: status/LGT2, type/bug-fix

#502 restore: Try to create tables in parallel
  lightning/glue/glue.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
  lightning/restore/tidb.go
  mock/glue.go
  mock/glue_checkpoint.go
Labels: rewarded, status/LGT2, status/PTAL

#543 Compatible for disk quota
  lightning/backend/local.go
Labels: status/LGT2

#524 backend/local: skip split regions if engine total size is smaller than region size
  lightning/backend/local.go
  lightning/backend/localhelper.go
  lightning/backend/localhelper_test.go
Labels: CanMerge, status/LGT2

#547 config: change redact log parameter name
  lightning/config/config.go
  lightning/config/global.go
  lightning/lightning.go
  lightning/log/log.go
  tidb-lightning.toml
Labels: Should Update Docs, status/LGT2, status/PTAL

#549 config: change redact log parameter name (#547)
  lightning/config/config.go
  lightning/config/global.go
  lightning/lightning.go
  lightning/log/log.go
  tidb-lightning.toml
Labels: status/LGT2

#551 backend/tidb: temporarily disable the strict-mode value check in tidb backend
  lightning/backend/local_test.go
  lightning/backend/tidb.go
  lightning/backend/tidb_test.go
Labels: status/LGT2

#510 test: fix invalid failpoint and integration test
  lightning/backend/local.go
  tests/local_backend/run.sh
Labels: CanMerge, status/LGT2

#555 test: fix s3 integration test
  tests/s3/config.toml
  tests/s3/run.sh
Labels: CanMerge, status/LGT2

#556 grafana dashboards support multiple cluster
  metrics/grafana/lightning.json
Labels: CanMerge, status/LGT2

#559 metrics: use tidb_cluster label get variable values
  metrics/grafana/lightning.json
Labels: status/LGT2

#506 restore: add importing progress and optimize the accuracy of restore progress
  lightning/backend/local.go
  lightning/metric/metric.go
  lightning/restore/restore.go
Labels: CanMerge, status/LGT2

#554 backend/local: fallback retryIngest to retryWrite
  lightning/backend/local.go
  lightning/backend/local_test.go
Labels: CanMerge, status/LGT3

#493 backend: implement disk quota
  go.mod1
  go.sum1
  lightning/backend/backend.go
  lightning/backend/backend_test.go
  lightning/backend/importer.go
  lightning/backend/local.go
  lightning/backend/local_test.go
  lightning/backend/tidb.go
  lightning/common/pause_test.go
  lightning/common/storage.go
  lightning/common/storage_test.go
  lightning/common/storage_unix.go
  lightning/common/storage_windows.go
  lightning/common/util.go
  lightning/common/util_test.go
  lightning/config/config.go
  lightning/config/config_test.go
  lightning/lightning_test.go
  lightning/metric/metric.go
  lightning/mydump/loader_test.go
  lightning/mydump/parquet_parser_test.go
  lightning/restore/restore.go
  lightning/restore/restore_test.go
  mock/backend.go
  tests/README.md
  tests/_utils/run_lightning
  tests/_utils/run_sql
  tests/checkpoint_columns/run.sh
  tests/checkpoint_parquet/run.sh
  tests/disk_quota/config.toml
  tests/disk_quota/data/disk_quota-schema-create.sql
  tests/disk_quota/data/disk_quota.t-schema.sql
  tests/disk_quota/data/disk_quota.t.0.sql
  tests/disk_quota/data/disk_quota.t.1.sql
  tests/disk_quota/data/disk_quota.t.2.sql
  tests/disk_quota/data/disk_quota.t.3.sql
  tests/disk_quota/run.sh
  tests/generated_columns/run.sh
  tests/local_backend/run.sh
  tests/parquet/run.sh
  tests/run.sh
  tidb-lightning.toml
Labels: CanMerge, status/LGT3, status/PTAL

#561 README: add more info
  README.md
Labels: status/LGT2
